#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: motd
# REQUIRE: mountcritremote
# BEFORE:  LOGIN

. /etc/rc.subr

name="motd"
desc="Update /etc/motd"
rcvar="update_motd"
start_cmd="motd_start"
stop_cmd=":"

PERMS="644"
MOTD_FILE="/etc/motd"

motd_start()
{
	#	Update kernel info in /etc/motd
	#	Must be done *before* interactive logins are possible
	#	to prevent possible race conditions.
	#
	check_startmsgs && echo -n 'Updating motd:'
	if [ ! -f ${MOTD_FILE} ]; then
		install -c -o root -g wheel -m ${PERMS} /dev/null ${MOTD_FILE}
	fi

	if [ ! -w ${MOTD_FILE} ]; then
		echo ' /etc/motd is not writable, update failed.'
		return
	fi

	T=`mktemp -t motd`
	uname -v | sed -e 's,^\([^#]*\) #\(.* [1-2][0-9][0-9][0-9]\).*/\([^\]*\) $,\1 (\3) #\2,' > ${T}
	awk '{if (NR == 1) {if ($1 == "FreeBSD" || $1 == "HardenedBSD") {next} else {print "\n"$0}} else {print}}' < ${MOTD_FILE} >> ${T}

	if ! cmp -s ${T} ${MOTD_FILE}; then
		install -c -o root -g wheel -m ${PERMS} ${T} ${MOTD_FILE}
	fi
	rm -f ${T}

	check_startmsgs && echo '.'
}

load_rc_config $name
run_rc_command "$1"
