FILES=	ca.hardenedbsd.org dnssec.key-2016-07-30

FILESDIR=	${SHAREDIR}/keys/hbsd-update/trusted
FILESMODE=	444

SYMLINKS=	\
		${SHAREDIR}/keys/hbsd-update/trusted/ca.hardenedbsd.org ${SHAREDIR}/keys/hbsd-update/trusted/5905e1b4.0 \
		${SHAREDIR}/keys/hbsd-update/trusted/dnssec.key-2016-07-30 ${SHAREDIR}/keys/hbsd-update/trusted/dnssec.key

.include <bsd.prog.mk>
