#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: dmesg
# REQUIRE: mountcritremote FILESYSTEMS
# BEFORE:  DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="dmesg"
desc="Save kernel boot messages to disk"
rcvar="dmesg_enable"
dmesg_file="/var/run/dmesg.boot"
start_cmd="do_dmesg"
stop_cmd=":"

do_dmesg()
{
	rm -f ${dmesg_file}

	case `/sbin/sysctl -n security.bsd.unprivileged_read_msgbuf` in
	1)
		( umask 022 ; /sbin/dmesg $rc_flags > ${dmesg_file} )
		;;
	*)
		( umask 077 ; /sbin/dmesg $rc_flags > ${dmesg_file} )
		;;
	esac
}

load_rc_config $name
run_rc_command "$1"
